# Used to replicate www.server.com on 127.0.0.1:3002 in the background
--- !ruby/object:OpenStruct 
table: 
  :storage_dir: /home/parkplace/.parkplace/storage
  :log_dir: /home/parkplace/.parkplace/log
  :replication: 
    :host: www.server.com
    :username: admin
    :secret_access_key: OtxrzxIsfpFjA7SwPzILwy8Bw21TLhquhboDYROV
    :enabled: true
  :host: 127.0.0.1
  :port: 3002
  :parkplace_dir: /home/parkplace/.parkplace
  :database: 
    :adapter: sqlite3
    :database: /home/parkplace/.parkplace/park.db
  :daemon: true
